// AUTO-GENERATED by tools/gen_posts.py — DO NOT EDIT MANUALLY
const posts = [
  {
    title: "第一篇：你好，博客！",
    date: "2026-02-19",
    slug: "2026-02-19-hello",
    desc: "我为什么做这个网站，以及接下来准备写什么。"
  },
  {
    title: "第二篇：学习新建博客",
    date: "2026-02-19",
    slug: "2026-02-19-test",
    desc: "新建博客/n记录我搭建个人网站后的第一周，以及接下来会怎么持续更新。"
  },
];

const el = document.getElementById('postList');
if (!el) {
  console.error("找不到 #postList：请检查 blog/index.html 是否有 <div id='postList'>");
} else {
  el.innerHTML = posts.map(p => `
    <a class="postitem" href="./post.html?p=${encodeURIComponent(p.slug)}">
      <div class="postmeta">
        <div class="posttitle">${p.title}</div>
        <div class="postdesc">${p.desc || ''}</div>
      </div>
      <div class="postdate">${p.date}</div>
    </a>
  `).join('');
}
