#!/usr/bin/env python3
# Generate blog/posts.js from blog/md/*.md (front matter)
import re
from pathlib import Path
from datetime import datetime

ROOT = Path(__file__).resolve().parents[1]
MD_DIR = ROOT / "blog" / "md"
OUT_JS = ROOT / "blog" / "posts.js"

FM_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n(.*)$", re.S)

def parse_front_matter(text: str):
  m = FM_RE.match(text.strip())
  if not m:
    return {}, text
  fm_raw, body = m.group(1), m.group(2)
  meta = {}
  for line in fm_raw.splitlines():
    if ":" not in line:
      continue
    k, v = line.split(":", 1)
    meta[k.strip()] = v.strip()
  return meta, body

def parse_date(s: str):
  # Expect YYYY-MM-DD; fallback to very old for sorting
  try:
    return datetime.strptime(s, "%Y-%m-%d")
  except Exception:
    return datetime(1970, 1, 1)

def main():
  if not MD_DIR.exists():
    raise SystemExit(f"Missing directory: {MD_DIR}")

  posts = []
  for md_path in sorted(MD_DIR.glob("*.md")):
    slug = md_path.stem
    text = md_path.read_text(encoding="utf-8", errors="replace")
    meta, _ = parse_front_matter(text)

    title = meta.get("title") or slug
    date = meta.get("date") or ""
    desc = meta.get("desc") or meta.get("description") or ""

    posts.append({
      "title": title,
      "date": date,
      "slug": slug,
      "desc": desc
    })

  posts.sort(key=lambda p: parse_date(p["date"]), reverse=True)

  def js_escape(s: str) -> str:
    return (s.replace("\\", "\\\\")
             .replace('"', '\\"')
             .replace("\n", "\\n"))

  lines = []
  lines.append("// AUTO-GENERATED by tools/gen_posts.py — DO NOT EDIT MANUALLY\n")
  lines.append("const posts = [\n")
  for p in posts:
    lines.append("  {\n")
    lines.append(f'    title: "{js_escape(p["title"])}",\n')
    lines.append(f'    date: "{js_escape(p["date"])}",\n')
    lines.append(f'    slug: "{js_escape(p["slug"])}",\n')
    lines.append(f'    desc: "{js_escape(p["desc"])}"\n')
    lines.append("  },\n")
  lines.append("];\n\n")
  lines.append("const el = document.getElementById('postList');\n")
  lines.append("if (!el) {\n")
  lines.append("  console.error(\"找不到 #postList：请检查 blog/index.html 是否有 <div id='postList'>\");\n")
  lines.append("} else {\n")
  lines.append("  el.innerHTML = posts.map(p => `\n")
  lines.append("    <a class=\"postitem\" href=\"./post.html?p=${encodeURIComponent(p.slug)}\">\n")
  lines.append("      <div class=\"postmeta\">\n")
  lines.append("        <div class=\"posttitle\">${p.title}</div>\n")
  lines.append("        <div class=\"postdesc\">${p.desc || ''}</div>\n")
  lines.append("      </div>\n")
  lines.append("      <div class=\"postdate\">${p.date}</div>\n")
  lines.append("    </a>\n")
  lines.append("  `).join('');\n")
  lines.append("}\n")

  OUT_JS.write_text("".join(lines), encoding="utf-8")
  print(f"✅ Generated: {OUT_JS} ({len(posts)} posts)")

if __name__ == "__main__":
  main()
