#!/usr/bin/env python3
# Generate blog/posts.js from blog/md/*.md and auto-bust cache by updating HTML query params.
import re
import time
from pathlib import Path
from datetime import datetime

ROOT = Path(__file__).resolve().parents[1]
MD_DIR = ROOT / "blog" / "md"
OUT_JS = ROOT / "blog" / "posts.js"

BLOG_INDEX = ROOT / "blog" / "index.html"
BLOG_POST = ROOT / "blog" / "post.html"

FM_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n(.*)$", re.S)

def parse_front_matter(text: str):
  m = FM_RE.match(text.strip())
  if not m:
    return {}, text
  fm_raw, body = m.group(1), m.group(2)
  meta = {}
  for line in fm_raw.splitlines():
    if ":" not in line:
      continue
    k, v = line.split(":", 1)
    meta[k.strip()] = v.strip()
  return meta, body

def parse_date(s: str):
  try:
    return datetime.strptime(s, "%Y-%m-%d")
  except Exception:
    return datetime(1970, 1, 1)

def js_escape(s: str) -> str:
  return (s.replace("\\", "\\\\")
           .replace('"', '\\"')
           .replace("\n", "\\n"))

def update_script_src(html: str, filename: str, version: str) -> str:
  """
  Replace any <script src="...filename..."> with <script src="...filename?v=version">
  Works for ./filename, ../filename, /filename, filename, and existing ?v=...
  """
  # capture quote style and prefix path up to filename
  pattern = re.compile(r'(<script[^>]*\bsrc=)(["\'])([^"\']*' + re.escape(filename) + r')(?:\?v=\d+)?(\2[^>]*>)(</script>)', re.I)
  def repl(m):
    before, q, path, after, end = m.group(1), m.group(2), m.group(3), m.group(4), m.group(5)
    return f'{before}{q}{path}?v={version}{after}{end}'
  return pattern.sub(repl, html)

def update_link_href(html: str, filename: str, version: str) -> str:
  """
  Replace any <link ... href="...filename..."> with ...filename?v=version
  """
  pattern = re.compile(r'(<link[^>]*\bhref=)(["\'])([^"\']*' + re.escape(filename) + r')(?:\?v=\d+)?(\2[^>]*>)', re.I)
  def repl(m):
    before, q, path, after = m.group(1), m.group(2), m.group(3), m.group(4)
    return f'{before}{q}{path}?v={version}{after}'
  return pattern.sub(repl, html)

def update_blog_html(version: str):
  # blog/index.html: styles.css, script.js, posts.js
  if BLOG_INDEX.exists():
    html = BLOG_INDEX.read_text(encoding="utf-8", errors="replace")
    html2 = html
    html2 = update_link_href(html2, "styles.css", version)
    html2 = update_script_src(html2, "script.js", version)
    html2 = update_script_src(html2, "posts.js", version)
    if html2 != html:
      BLOG_INDEX.write_text(html2, encoding="utf-8")

  # blog/post.html: styles.css, script.js, md.js
  if BLOG_POST.exists():
    html = BLOG_POST.read_text(encoding="utf-8", errors="replace")
    html2 = html
    html2 = update_link_href(html2, "styles.css", version)
    html2 = update_script_src(html2, "script.js", version)
    html2 = update_script_src(html2, "md.js", version)
    if html2 != html:
      BLOG_POST.write_text(html2, encoding="utf-8")

def main():
  if not MD_DIR.exists():
    raise SystemExit(f"Missing directory: {MD_DIR}")

  posts = []
  for md_path in sorted(MD_DIR.glob("*.md")):
    slug = md_path.stem
    text = md_path.read_text(encoding="utf-8", errors="replace")
    meta, _ = parse_front_matter(text)

    title = meta.get("title") or slug
    date = meta.get("date") or ""
    desc = meta.get("desc") or meta.get("description") or ""

    posts.append({
      "title": title,
      "date": date,
      "slug": slug,
      "desc": desc
    })

  posts.sort(key=lambda p: parse_date(p["date"]), reverse=True)

  lines = []
  lines.append("// AUTO-GENERATED by tools/gen_posts.py — DO NOT EDIT MANUALLY\n\n")
  lines.append("const posts = [\n")
  for p in posts:
    lines.append("  {\n")
    lines.append(f'    title: "{js_escape(p["title"])}",\n')
    lines.append(f'    date: "{js_escape(p["date"])}",\n')
    lines.append(f'    slug: "{js_escape(p["slug"])}",\n')
    lines.append(f'    desc: "{js_escape(p["desc"])}"\n')
    lines.append("  },\n")
  lines.append("];\n\n")
  lines.append("const el = document.getElementById('postList');\n")
  lines.append("if (!el) {\n")
  lines.append("  console.error(\"找不到 #postList：请检查 blog/index.html 是否有 <div id='postList'>\");\n")
  lines.append("} else {\n")
  lines.append("  el.innerHTML = posts.map(p => `\n")
  lines.append("    <a class=\"postitem\" href=\"./post.html?p=${encodeURIComponent(p.slug)}\">\n")
  lines.append("      <div class=\"postmeta\">\n")
  lines.append("        <div class=\"posttitle\">${p.title}</div>\n")
  lines.append("        <div class=\"postdesc\">${p.desc || ''}</div>\n")
  lines.append("      </div>\n")
  lines.append("      <div class=\"postdate\">${p.date}</div>\n")
  lines.append("    </a>\n")
  lines.append("  `).join('');\n")
  lines.append("}\n")

  OUT_JS.write_text("".join(lines), encoding="utf-8")

  version = str(int(time.time()))
  update_blog_html(version)

  print(f"✅ Generated: {OUT_JS} ({len(posts)} posts)")
  print(f"✅ Cache bust version set to v={version} in blog/index.html and blog/post.html")

if __name__ == "__main__":
  main()
